### ISSUE TITLE
Mimic kraken mode error

### ISSUE THREAD

**Issue by simonepignotti** [prophyle/prophyle#310]
The following error was encountered using the option `-M` of `prophyle classify`, corresponding to `prophyle_assignment.py -m h1 -f kraken -L -X`:
```
Traceback (most recent call last):
  File "/home/sp386/.anaconda3/bin/prophyle_assignment.py", line 6, in <module>
    sys.exit(prophyle.prophyle_assignment.main())
  File "/home/sp386/.anaconda3/lib/python3.6/site-packages/prophyle/prophyle_assignment.py", line 798, in main
    kmer_lca=args.kmer_lca,
  File "/home/sp386/.anaconda3/lib/python3.6/site-packages/prophyle/prophyle_assignment.py", line 705, in assign_all_reads
    assignment.process_read(krakline, form=form, measure=measure)
  File "/home/sp386/.anaconda3/lib/python3.6/site-packages/prophyle/prophyle_assignment.py", line 108, in process_read
    self.compute_assignments()
  File "/home/sp386/.anaconda3/lib/python3.6/site-packages/prophyle/prophyle_assignment.py", line 169, in compute_assignments
    self.ass_dict = {nodename: self.evaluate_single_assignment(nodename) for nodename in nodenames}
  File "/home/sp386/.anaconda3/lib/python3.6/site-packages/prophyle/prophyle_assignment.py", line 169, in <dictcomp>
    self.ass_dict = {nodename: self.evaluate_single_assignment(nodename) for nodename in nodenames}
  File "/home/sp386/.anaconda3/lib/python3.6/site-packages/prophyle/prophyle_assignment.py", line 210, in evaluate_single_assignment
    'h2': [hit / self.tree_index.nodename_to_kmercount[nodename]],
ZeroDivisionError: division by zero
```
I believe this could happen even with the standard parameters, and it just becomes more probable with the k-mer level LCA, since the k-mer count of the resulting node is more likely to be 0. It should therefore be fixed ASAP.

What do you think we should output as `h2` when the k-mer count is 0?

**Comment by karel-brinda** [comment]
I think this happens when LCA is computed from nodes with different bit-masks. Thank you for reporting.

**Comment by karel-brinda** [comment]
Could you figure out which read causes this error, please?
