### ISSUE TITLE
Cannot use process substitution as input for prophyle classify

### ISSUE THREAD

**Issue by simonepignotti** [prophyle/prophyle#314]
Due to the tests at lines 855 and 857 of `prophyle classify`, it is not possible to use process substitution.
Switching those lines to `..., allow_pipes=True)` does not work either.

Example of error message:
```
$ prophyle classify idx <(head -n 400 reads.fastq)
[prophyle] 2018-05-16 14:23:16 Classification started
[prophyle] 2018-05-16 14:23:16 Shell command: make -j -s -C ~/prophyle
[prophyle] 2018-05-16 14:23:17 Finished (0.8 MB used): make -j -s -C ~/prophyle
[prophyle] 2018-05-16 14:23:17 Automatic detection of k-mer length: k=25
Traceback (most recent call last):
  File "prophyle.py", line 1624, in <module>
    main()
  File "prophyle.py", line 1554, in main
    prophyle_conf_string=prophyle_conf_string,  # already preprocessed
  File "prophyle.py", line 857, in prophyle_classify
    pro.test_files(fq_fn, allow_pipes=False)
  File "prophylelib.py", line 392, in test_files
    assert is_file, 'File "{}" is a process substitution or a device.'.format(fn)
AssertionError: File "/dev/fd/63" is a process substitution or a device.
```

With `allow_pipes=True`:
```
klcp_loading    13.54s
[bwa_seq_open] fail to open file '/dev/fd/63' : No such file or directory
```

**Comment by simonepignotti** [comment]
Sorry!
