### ISSUE TITLE
prophyle_assignment: not enough values to unpack (expected 2, got 1)

### ISSUE THREAD

**Issue by karel-brinda** [prophyle/prophyle#320]
```
[prophyle] 2018-05-31 23:47:04 Shell command: make -j -s -C /home/kb219/miniconda/envs/p/lib/python3.6/site-packages/prophyle
klcp_loading    0.17s
Traceback (most recent call last):
  File "/home/kb219/miniconda/envs/p/bin/prophyle_assignment.py", line 11, in <module>
    load_entry_point('prophyle==0.3.2.0', 'console_scripts', 'prophyle_assignment.py')()
  File "/home/kb219/miniconda/envs/p/lib/python3.6/site-packages/prophyle/prophyle_assignment.py", line 812, in main
    kmer_lca=args.kmer_lca,
  File "/home/kb219/miniconda/envs/p/lib/python3.6/site-packages/prophyle/prophyle_assignment.py", line 719, in assign_all_reads
    assignment.process_read(krakline, form=form, measure=measure)
  File "/home/kb219/miniconda/envs/p/lib/python3.6/site-packages/prophyle/prophyle_assignment.py", line 105, in process_read
    self.krakline_parser.parse_krakline(krakline)
  File "/home/kb219/miniconda/envs/p/lib/python3.6/site-packages/prophyle/prophyle_assignment.py", line 637, in parse_krakline
    (ids, count) = block.split(":")
ValueError: not enough values to unpack (expected 2, got 1)

```

**Comment by rchikhi** [comment]
I get that bug too

**Comment by karel-brinda** [comment]
How Ryan, could you please update to the commit `b55e026`? It should be fixed there.

**Comment by karel-brinda** [comment]
How Rayan, could you please update to the commit b55e026? It should be fixed there.

**Comment by karel-brinda** [comment]
It's not a typical use case, but this is not why it's crashing. There's a problem with fixed buffer sizes in one of the subprograms. The fix in `b55e026` doesn't address the problem, but makes ProPhyle not crash when this happens.

**Comment by rchikhi** [comment]
Using that commit, no more crash. I can even confirm that the resulting classification of that long sequence is satisfactory. Thanks.
