### ISSUE TITLE
Bioconda env for prophyle:  "CApath: none"

### ISSUE THREAD

**Issue by karel-brinda** [prophyle/prophyle#326]
```
$ ./test1_index.sh 

./prophyle/prophyle.py download bacteria
[prophyle] 2018-10-11 14:40:14 Downloading "bacteria" started
[prophyle] 2018-10-11 14:40:14 Downloading library '/Users/karel/prophyle'
[prophyle] 2018-10-11 14:40:14 Shell command: cd /Users/karel/prophyle/bacteria/.. && curl -O https://zenodo.org/record/1054426/files/bacteria.nw && curl https://zenodo.org/record/1054426/files/bacteria.tar.gz | tar xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (77) error setting certificate verify locations:
  CAfile: /Users/karel/miniconda/envs/prophyle/ssl/cacert.pem
  CApath: none
[prophyle] 2018-10-11 14:40:14 Unfinished, an error occurred (error code 77, 0.3 MB used): cd /Users/karel/prophyle/bacteria/.. && curl -O https://zenodo.org/record/1054426/files/bacteria.nw && curl https://zenodo.org/record/1054426/files/bacteria.tar.gz | tar xz
Traceback (most recent call last):
  File "./prophyle/prophyle.py", line 1609, in <module>
    main()
  File "./prophyle/prophyle.py", line 1486, in main
    force=args.force,
  File "./prophyle/prophyle.py", line 323, in prophyle_download
    pro.run_safe(cmd)
  File "/Users/karel/github/my/prophyle/prophyle/prophylelib.py", line 483, in run_safe
    raise RuntimeError("A command failed, see messages above.")
RuntimeError: A command failed, see messages above.
```

**Comment by karel-brinda** [comment]
This is not a ProPhyle issue –  it's an issue of curl in Conda.
