### ISSUE TITLE
RecursionError: maximum recursion depth exceeded while pickling an object

### ISSUE THREAD

**Issue by karel-brinda** [prophyle/prophyle#337]
```
[prophyle] 2020-10-10 16:43:53 Shell command: make -j -s -C /home/kb219/miniconda/envs/mashtree/lib/python3.7/site-packages/prophyle
Autocompleting FASTA paths
Autocompleting internal node names
Traceback (most recent call last):
  File "/home/kb219/miniconda/envs/mashtree/bin/prophyle_propagation_makefile.py", line 11, in <module>
    sys.exit(main())
  File "/home/kb219/miniconda/envs/mashtree/lib/python3.7/site-packages/prophyle/prophyle_propagation_makefile.py", line 415, in main
    makefile_fn=makefile_fn,
  File "/home/kb219/miniconda/envs/mashtree/lib/python3.7/site-packages/prophyle/prophyle_propagation_makefile.py", line 197, in __init__
    self.tree = pro.minimal_subtree(tree)
  File "/home/kb219/miniconda/envs/mashtree/lib/python3.7/site-packages/prophyle/prophylelib.py", line 240, in minimal_subtree
    tree_copy = tree.copy()
  File "/home/kb219/miniconda/envs/mashtree/lib/python3.7/site-packages/ete3/coretype/tree.py", line 1440, in copy
    new_node = six.moves.cPickle.loads(six.moves.cPickle.dumps(self, 2))
RecursionError: maximum recursion depth exceeded while pickling an object
```

**Comment by karel-brinda** [comment]
Workaround: add `sys.setrecursionlimit(10000)` to `prophylelib.py`
