### ISSUE TITLE
Avoid *

### ISSUE THREAD

**Issue by karel-brinda** [prophyle/prophyle#340]
```
[prophyle] 2020-10-11 23:51:19 Unfinished, an error occurred (error code 1, 6.0 MB used): cat mycobacterium_tuberculosis/propagation/*.tsv > mycobacterium_tuberculosis/index.fa.kmers.tsv
Error: K-mer statistics could not be created.
Traceback (most recent call last):
  File "/home/kb219/miniconda/envs/mashtree/bin/prophyle", line 11, in <module>
    sys.exit(main())
  File "/home/kb219/miniconda/envs/mashtree/lib/python3.7/site-packages/prophyle/prophyle.py", line 1509, in main
    autocomplete=args.autocomplete,
  File "/home/kb219/miniconda/envs/mashtree/lib/python3.7/site-packages/prophyle/prophyle.py", line 715, in prophyle_index
    _propagation_postprocessing(index_dir, index_tree_1, index_tree_2)
  File "/home/kb219/miniconda/envs/mashtree/lib/python3.7/site-packages/prophyle/prophyle.py", line 510, in _propagation_postprocessing
    thr_exc=True,
  File "/home/kb219/miniconda/envs/mashtree/lib/python3.7/site-packages/prophyle/prophylelib.py", line 483, in run_safe
    raise RuntimeError("A command failed, see messages above.")
RuntimeError: A command failed, see messages above.

```

**Comment by karel-brinda** [comment]
Duplicate of #350
